let trocar = document.querySelector("#botao")
let bodyclaro = document.querySelector("body")
let umclaro = document.querySelector(".um")
let doisclaro = document.querySelector(".dois")
let tresclaro = document.querySelector(".tres")
let quatroclaro = document.querySelector(".quatro")
let h1claro = document.querySelector(".h1")
let h1doisclaro = document.querySelector(".h1dois")
let pclaro = document.querySelector(".p")
trocar.addEventListener("click", () => {
    bodyclaro.classList.toggle("bodyclaro")
    umclaro.classList.toggle("divsclaro")
    doisclaro.classList.toggle("divsdoisclaro")
    tresclaro.classList.toggle("divsclaro")
    quatroclaro.classList.toggle("divsdoisclaro") 
    h1claro.classList.toggle("h1claro")
    h1doisclaro.classList.toggle("h1claro")
    pclaro.classList.toggle("pclaro")
    console.log(trocar)
});